require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'spec/support/**/*.rb'
    - 'lib/tasks/generate_invoice_xml.rake'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/generate_invoice_xml.rake'

Metrics/MethodLength:
  Exclude:
    - 'lib/tasks/generate_invoice_xml.rake'

Rails/HasAndBelongsToMany:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/Output:
  Exclude:
    - db/seeds.rb

RSpec/AnyInstance:
  Enabled: false
RSpec/EmptyExampleGroup:
  Exclude:
    - spec/integration/**/*.rb
RSpec/ExampleLength:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Max: 6
RSpec/ScatteredSetup:
  Exclude:
    - spec/integration/**/*.rb
RSpec/VariableName:
  Exclude:
    - spec/integration/**/*.rb

Style/BlockDelimiters:
  Exclude:
    - spec/**/*_spec.rb
Style/Documentation:
  Enabled: false
Style/MixinUsage:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.1.0
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/**
    - db/schema.rb
    - db/migrate/**
    - config/initializers/**
    - log/**
    - tmp/**
    - vendor/bundle/**
